// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: user.sql

package db

import (
	"context"
	"database/sql"

	"github.com/google/uuid"
)

const createUser = `-- name: createUser :one
INSERT INTO users (name, email, password_hash, is_active)
VALUES ($1, $2, $3, true)
RETURNING id, name, email, password_hash
`

type createUserParams struct {
	Name         sql.NullString `json:"name"`
	Email        string         `json:"email"`
	PasswordHash sql.NullString `json:"password_hash"`
}

type createUserRow struct {
	ID           uuid.UUID      `json:"id"`
	Name         sql.NullString `json:"name"`
	Email        string         `json:"email"`
	PasswordHash sql.NullString `json:"password_hash"`
}

func (q *Queries) createUser(ctx context.Context, arg createUserParams) (createUserRow, error) {
	row := q.db.QueryRowContext(ctx, createUser, arg.Name, arg.Email, arg.PasswordHash)
	var i createUserRow
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Email,
		&i.PasswordHash,
	)
	return i, err
}

const getUserByEmail = `-- name: getUserByEmail :one
SELECT id, name, email, password_hash
FROM users
WHERE email = $1 AND is_active = true
`

type getUserByEmailRow struct {
	ID           uuid.UUID      `json:"id"`
	Name         sql.NullString `json:"name"`
	Email        string         `json:"email"`
	PasswordHash sql.NullString `json:"password_hash"`
}

func (q *Queries) getUserByEmail(ctx context.Context, email string) (getUserByEmailRow, error) {
	row := q.db.QueryRowContext(ctx, getUserByEmail, email)
	var i getUserByEmailRow
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Email,
		&i.PasswordHash,
	)
	return i, err
}

const getUserByID = `-- name: getUserByID :one
SELECT id, name, email, password_hash
FROM users
WHERE id = $1 AND is_active = true
`

type getUserByIDRow struct {
	ID           uuid.UUID      `json:"id"`
	Name         sql.NullString `json:"name"`
	Email        string         `json:"email"`
	PasswordHash sql.NullString `json:"password_hash"`
}

func (q *Queries) getUserByID(ctx context.Context, id uuid.UUID) (getUserByIDRow, error) {
	row := q.db.QueryRowContext(ctx, getUserByID, id)
	var i getUserByIDRow
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Email,
		&i.PasswordHash,
	)
	return i, err
}
